### ISSUE TITLE
Send notification only when Quality Gate fails

### ISSUE THREAD

**Issue by poznachowski** [kogitant/sonar-slack-notifier-plugin#1]
I would find really useful to send notifications only if Quality Gate fails.
Possibly, configurable per project.

If you don't find it worth putting on your radar, I'd be happy to contribute.

**Comment by kogitant** [comment]
Hi,
good idea. Let me see if I can whip something up. Pull request is of course welcome too.

**Comment by poznachowski** [comment]
PR #3 already submitted.

**Comment by kogitant** [comment]
Pull request merged, 2.0 release https://github.com/kogitant/sonar-slack-notifier-plugin/releases/tag/2.0 includes this. Thanks for the contribution!
