### ISSUE TITLE
Incorrect "projectUrl" in SonarQube 6.3.0

### ISSUE THREAD

**Issue by dimabutenko** [kogitant/sonar-slack-notifier-plugin#10]
[sonar-slack-notifier-plugin/src/main/java/com/koant/sonar/slacknotifier/extension/task/SlackPostProjectAnalysisTask.java](url)
`private String projectUrl(String projectKey) {
        return getSonarServerUrl() + "overview?id=" + projectKey;
    }`

![screen-d butenko-20170403-112753](https://cloud.githubusercontent.com/assets/6714627/24601226/c11a340c-1860-11e7-92ea-b9ad55f00413.png)

https://jira.sonarsource.com/browse/SONAR-7934

Can you please check this and fix?

**Comment by sleepy86** [comment]
The string "**overview**?id=" must be replaced with "**dashboard**?id=".

**Comment by samarkumar1** [comment]
It will be great if you can checkin the fix

**Comment by samarkumar1** [comment]
[cks-slack-notifier-2.1.zip](https://github.com/kogitant/sonar-slack-notifier-plugin/files/1316692/cks-slack-notifier-2.1.zip)
updated the code with updated url as "dashboard?id=", please refer to attach zip file which contains the updated jar file for version 2.1

**Comment by kogitant** [comment]
Sorry for the delay. I should be able to merge this to master on monday.

**Comment by kogitant** [comment]
PR merged. Sorry that this took forever.
