### ISSUE TITLE
Support wildcards in project key parameter

### ISSUE THREAD

**Issue by poznachowski** [kogitant/sonar-slack-notifier-plugin#2]
Proposition:
Add support for wildcards in project key parameter. I find option of asterisk '*' at the end of the key sufficient.

Rationale:
Currently the plugin takes project key (ex. `com.company:project`) exactly as is.

If someone would like to make analysis on branches (via `sonar.branch` parameter), he would need to make appropriate changes in the plugin configuration (project key with branch would look like: `com.company:project:branch_name`). Considering some flow with short-term branches it would be really annoying.

If asterisk wildcard is implemented, I can specify `com.company:project:*` to send analysis of each projects` branches to a single Slack channel.

**Comment by kogitant** [comment]
Hi,
excellent idea. I'll look into this.

**Comment by poznachowski** [comment]
I already submit PR for this: #3 :)

**Comment by kogitant** [comment]
Pull request merged, 2.0 release https://github.com/kogitant/sonar-slack-notifier-plugin/releases/tag/2.0 includes this. Thanks for the contribution!

**Comment by lemmebee** [comment]
Hi, I'm having a problem using project key parameter and configuring slack channel! Could you please help me with this?
